<?php

/**
 * @var \MyBC\Weather\Block\Weather $block
 */

?>

<!-- <div id="cont_63a06cc49ba6011046904f51f97f68d8"><script type="text/javascript" async src="https://www.theweather.com/wid_loader/63a06cc49ba6011046904f51f97f68d8"></script></div> -->

<?php
// Your code here!
$ch = curl_init();
// IMPORTANT: the below line is a security risk, read https://paragonie.com/blog/2017/10/certainty-automated-cacert-pem-management-for-php-software
// in most cases, you should set it to true
$url = 'http://api.openweathermap.org/data/2.5/onecall?lat=21.027763&lon=105.834160&units=metric&lang=vi&APPID=';
$api_key = '8ce73c1c103b372de3e5066d67ed7b15';
$url = $url . $api_key;
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, $url);
$result = curl_exec($ch);
curl_close($ch);

$today = date('w');

$obj = json_decode($result);
$current = $obj->current;
$daily = $obj->daily;
?>

<?php
    function getDayofWeekName($dayOfWeak) {
        $dayOfWeak = $dayOfWeak % 7;
        switch ($dayOfWeak) {
            case 0:
                return 'Chủ nhật';

            case 1:
                return 'Thứ hai';

            case 2:
                return 'Thứ ba';

            case 3:
                return 'Thứ tư';

            case 4:
                return 'Thứ năm';

            case 5:
                return 'Thứ sáu';

            case 6:
                return 'Thứ bảy';

            default:
                return '';
        }
    }
    function getIconUrl($iconName) {
        return 'http://openweathermap.org/img/w/' . $iconName . '.png';
    }
?>

<div class="hotfix">
    <div class="mybc-weather-container">
        <div class="weather-side">
            <div class="weather-gradient"></div>
            <div class="date-mybc-weather-container">
                <h2 class="date-dayname"><?php echo getDayofWeekName($today); ?></h2><span class="date-day"><?php echo date("d/m/Y"); ?></span>Địa điểm: <span class="location">Hanoi, VN</span></div>
            <div class="weather-mybc-weather-container"><img src="<?php echo getIconUrl($current->weather[0]->icon); ?>" style="width:80%" />
                <h1 class="weather-temp"><?php echo $current->temp; ?> °C</h1>
                <h3 class="weather-desc"><?php echo $current->weather[0]->description; ?></h3>
            </div>
        </div>
        <div class="info-side">
            <div class="today-info-mybc-weather-container">
                <div class="today-info">
                    <div class="precipitation"> <span class="title">Áp suất không khí:</span><span class="value"><?php echo $current->pressure; ?> hpa</span>
                        <div class="clear"></div>
                    </div>
                    <div class="humidity"> <span class="title">Độ ẩm không khí:</span><span class="value"><?php echo $current->humidity; ?> %</span>
                        <div class="clear"></div>
                    </div>
                    <div class="wind"> <span class="title">Tốc độ gió:</span><span class="value"><?php echo $current->wind_speed; ?> km/h</span>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="week-mybc-weather-container">
                <ul class="week-list">
                    <li class="active">
                        <img src="<?php echo getIconUrl($current->weather[0]->icon); ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today); ?></span>
                        <span class="day-temp"><?php echo $current->temp; ?>°C</span>
                    </li>
                    <li>
                        <img src="<?php echo getIconUrl($daily[1]->weather[0]->icon) ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today+1); ?></span>
                        <span class="day-temp"><?php echo $daily[1]->temp->day; ?> °C</span>
                    </li>
                    <li>
                        <img src="<?php echo getIconUrl($daily[2]->weather[0]->icon) ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today+2); ?></span>
                        <span class="day-temp"><?php echo $daily[2]->temp->day; ?> °C</span>
                    </li>
                    <li>
                        <img src="<?php echo getIconUrl($daily[3]->weather[0]->icon) ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today+3); ?></span>
                        <span class="day-temp"><?php echo $daily[3]->temp->day; ?> °C</span>
                    </li>
                    <li>
                        <img src="<?php echo getIconUrl($daily[4]->weather[0]->icon) ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today+4); ?></span>
                        <span class="day-temp"><?php echo $daily[4]->temp->day; ?> °C</span></li>
                    <li>
                        <img src="<?php echo getIconUrl($daily[5]->weather[0]->icon) ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today+5); ?></span>
                        <span class="day-temp"><?php echo $daily[5]->temp->day; ?> °C</span>
                    </li>
                    <li>
                        <img src="<?php echo getIconUrl($daily[6]->weather[0]->icon) ?>" />
                        <span class="day-name"><?php echo getDayofWeekName($today+6); ?></span>
                        <span class="day-temp"><?php echo $daily[6]->temp->day; ?> °C</span>
                    </li>
                    <div class="clear"></div>
                </ul>
            </div>
            <div class="location-mybc-weather-container"><button class="location-button"> <i data-feather="map-pin"></i><span>Change location</span></button></div>
        </div>
    </div>
</div>


<script>
    feather.replace()
</script>

<style>
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700,900&display=swap');

:root {
    --gradient: linear-gradient( 135deg, #72EDF2 10%, #5151E5 100%);
}

* {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    line-height: 1.25em;
}

.clear {
    clear: both;
}

/* body {
margin: 0;
width: 100%;
height: 100vh;
font-family: 'Montserrat', sans-serif;
background-color: #343d4b;
display: -webkit-box;
display: -ms-flexbox;
display: flex;
-webkit-box-align: center;
-ms-flex-align: center;
align-items: center;
-webkit-box-pack: center;
-ms-flex-pack: center;
justify-content: center;
} */

.hotfix{
    margin: 0;
    width: 100%;
    font-family: 'Montserrat', sans-serif;
    /* background-color: #343d4b; */
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    justify-content: center;
}

.mybc-weather-container {
    border-radius: 25px;
    -webkit-box-shadow: 0 0 70px -10px rgba(0, 0, 0, 0.2);
    box-shadow: 0 0 70px -10px rgba(0, 0, 0, 0.2);
    background-color: #222831;
    color: #ffffff;
    height: 400px;
}

.weather-side {
    position: relative;
    height: 100%;
    border-radius: 25px;
    background-image: url("https://images.unsplash.com/photo-1559963110-71b394e7494d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80");
    width: 300px;
    -webkit-box-shadow: 0 0 20px -10px rgba(0, 0, 0, 0.2);
    box-shadow: 0 0 20px -10px rgba(0, 0, 0, 0.2);
    -webkit-transition: -webkit-transform 300ms ease;
    transition: -webkit-transform 300ms ease;
    -o-transition: transform 300ms ease;
    transition: transform 300ms ease;
    transition: transform 300ms ease, -webkit-transform 300ms ease;
    -webkit-transform: translateZ(0) scale(1.02) perspective(1000px);
    transform: translateZ(0) scale(1.02) perspective(1000px);
    float: left;
}

.weather-side:hover {
    -webkit-transform: scale(1.1) perspective(1500px) rotateY(10deg);
    transform: scale(1.1) perspective(1500px) rotateY(10deg);
}

.weather-gradient {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background-image: var(--gradient);
    border-radius: 25px;
    opacity: 0.8;
}

.date-mybc-weather-container {
    position: absolute;
    top: 25px;
    left: 25px;
}

.date-dayname {
    margin: 0;
}

.date-day {
    display: block;
}

.location {
    display: inline-block;
    margin-top: 10px;
}

.location-icon {
    display: inline-block;
    height: 0.8em;
    width: auto;
    margin-right: 5px;
}

.weather-mybc-weather-container {
    position: absolute;
    bottom: 25px;
    left: 25px;
}

.weather-icon.feather {
    height: 60px;
    width: auto;
}

.weather-temp {
    margin: 0;
    font-weight: 700;
    font-size: 4em;
}

.weather-desc {
    margin: 0;
}

.info-side {
    position: relative;
    float: left;
    height: 100%;
    padding-top: 25px;
}

.today-info {
    padding: 15px;
    margin: 0 25px 25px 25px;
    /* 	box-shadow: 0 0 50px -5px rgba(0, 0, 0, 0.25); */
    border-radius: 10px;
}

.today-info>div:not(:last-child) {
    margin: 0 0 10px 0;
}

.today-info>div .title {
    float: left;
    font-weight: 700;
}

.today-info>div .value {
    float: right;
}

.week-list {
    list-style-type: none;
    padding: 0;
    margin: 10px 35px;
    -webkit-box-shadow: 0 0 50px -5px rgba(0, 0, 0, 0.25);
    box-shadow: 0 0 50px -5px rgba(0, 0, 0, 0.25);
    border-radius: 10px;
    background: #
}

.week-list>li {
    float: left;
    padding: 15px;
    cursor: pointer;
    -webkit-transition: 200ms ease;
    -o-transition: 200ms ease;
    transition: 200ms ease;
    border-radius: 10px;
}

.week-list>li:hover {
    -webkit-transform: scale(1.1);
    -ms-transform: scale(1.1);
    transform: scale(1.1);
    background: #fff;
    color: #222831;
    -webkit-box-shadow: 0 0 40px -5px rgba(0, 0, 0, 0.2);
    box-shadow: 0 0 40px -5px rgba(0, 0, 0, 0.2)
}

.week-list>li.active {
    background: #fff;
    color: #222831;
    border-radius: 10px;
}

.week-list>li .day-name {
    display: block;
    margin: 10px 0 0 0;
    text-align: center;
}

.week-list>li .day-icon {
    display: block;
    height: 30px;
    width: auto;
    margin: 0 auto;
}

.week-list>li .day-temp {
    display: block;
    text-align: center;
    margin: 10px 0 0 0;
    font-weight: 700;
}

.location-mybc-weather-container {
    padding: 25px 35px;
}

.location-button {
    outline: none;
    width: 100%;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    border: none;
    border-radius: 25px;
    padding: 10px;
    font-family: 'Montserrat', sans-serif;
    background-image: var(--gradient);
    color: #ffffff;
    font-weight: 700;
    -webkit-box-shadow: 0 0 30px -5px rgba(0, 0, 0, 0.25);
    box-shadow: 0 0 30px -5px rgba(0, 0, 0, 0.25);
    cursor: pointer;
    -webkit-transition: -webkit-transform 200ms ease;
    transition: -webkit-transform 200ms ease;
    -o-transition: transform 200ms ease;
    transition: transform 200ms ease;
    transition: transform 200ms ease, -webkit-transform 200ms ease;
}

.location-button:hover {
    -webkit-transform: scale(0.95);
    -ms-transform: scale(0.95);
    transform: scale(0.95);
}

.location-button .feather {
    height: 1em;
    width: auto;
    margin-right: 5px;
}
</style>
