<?php /** @var $block \MyBC\News\Block\PostList */ ?>
<h1><?php echo __('Những tin tức gần đây nhất') ?></h1>
<ul class="news-post-list">
<?php /** @var $post \MyBC\News\Model\Post */ ?>
<?php foreach ($block->getPosts() as $post): ?>
    <li class="news-post-list-item">
        <h3 class="news-post-item-title">
            <a href="<?php echo $post->getUrlKey() ?>"><?php echo $post->getTitle() ?></a>
        </h3>

        <div class="news-post-item-content">
            <?php echo $post->getContent(); ?>
        </div>

        <div class="news-post-item-meta">
            <strong><?php echo __('Ngày đăng tải:') ?></strong> <?php echo $post->getCreationTime() ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>
