<?php /** @var $block \MyBC\News\Block\PostList */ ?>
<h1><?php echo __('Latest News Posts') ?></h1>
<ul class="News-post-list">
<?php /** @var $post \MyBC\News\Model\Post */ ?>
<?php foreach ($block->getPosts() as $post): ?>
    <li class="News-post-list-item">
        <h3 class="News-post-item-title">
            <a href="<?php echo $post->getUrl() ?>"><?php echo $post->getTitle() ?></a>
        </h3>

        <div class="News-post-item-content">
            <?php echo $post->getContent(); ?>
        </div>

        <div class="News-post-item-meta">
            <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getPublishedDate() ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>
