<?php
/** @var $block \MyBC\News\Block\PostView */
/** @var $post \MyBC\News\Model\Post */
$post = $block->getPost();
?>
<h1 class="news-post-item-title"><?php echo $post->getTitle() ?></h1>

<div class="news-post-item-content">
    <?php echo $post->getContent(); ?>
</div>

<div class="news-post-item-meta">
    <strong><?php echo __('Ngày đăng tải:') ?></strong> <?php echo $post->getCreationTime() ?>
</div>
