<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<?php

/**
* @var \MyBC\LatestNews\Block\LatestNews $block
*/

?>

<div id="content"></div>

<?php

$ch = curl_init();
$url = 'https://api.rss2json.com/v1/api.json?rss_url=https://vnexpress.net/rss/tin-moi-nhat.rss';
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, $url);
$result = curl_exec($ch);
curl_close($ch);
$data = json_decode($result);

?>

<div class="container" style="margin-top: 40px;">
    <div class="row">
        <?php foreach ($data->items as $k => $item): ?>
            <?php
                $desc = strip_tags($item->description);
                $desc = substr($desc, 0, 125);
                $desc = substr($desc, 0, strrpos($desc, ' ')) . "...";
            ?>
            <div class="col-sm-6">
                <div class="card flex-md-row mb-4 box-shadow h-md-250 hovereffect">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="card-body d-flex flex-column align-items-start">
                                <strong class="d-inline-block mb-2 text-primary">VnExpress</strong>
                                <h4 class="mb-0">
                                    <a class="text-dark font-weight-bold" href="<?php echo $item->link ?>"><?php echo $item->title ?></a>
                                </h4>
                                <br>
                                <span><?php echo $item->pubDate ?></span>
                                <p class="card-text mb-auto"><?php echo $desc ?></p>
                                <span>
                                <a href="<?php echo $item->link ?>" class="readmore">Đọc thêm<span class="label label-danger"><span class="glyphicon glyphicon-circle-arrow-right"></span></span></a>
                                </span>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <a href="<?php echo $item->link ?>">
                                <img alt="bài báo này không có ảnh" class="card-img-right flex-auto d-none d-md-block w-100 img-responsive" data-src="<?php echo $item->thumbnail ?>" src="<?php echo $item->thumbnail ?>" data-holder-rendered="true">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<style>

.readmore {
    color: red!important;
}

.news-img {
    background: url('https://bitsofco.de/content/images/2018/12/Screenshot-2018-12-16-at-21.06.29.png') no-repeat scroll 0 0;
}

.hovereffect {
    transition: all 0.2s ease;
}

.hovereffect:hover {
    box-shadow:
    2px 2px #1d96b2,
    4px 4px #1d96b2,
    6px 6px #1d96b2;
    -webkit-transform: translate(-8px, -8px);
    transform: translate(-8px, -8px);
}

</style>
