<?php

/**
 * @var \MyBC\LatestNews\Block\LatestNews $block
 */

?>

<div id="content"></div>

<script>
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            appendNewsContent(JSON.parse(this.responseText).items);
        }
    };
    xhttp.open("GET", "https://api.rss2json.com/v1/api.json?rss_url=" + "https://vnexpress.net/rss/tin-moi-nhat.rss", true);
    xhttp.send();

    function htmlToElement(html) {
        var template = document.createElement('template');
        html = html.trim();
        template.innerHTML = html;
        return template.content.firstChild;
    }

    function appendNewsContent(data) {

        var content = document.getElementById("content");
        // content.appendChild(htmlToElement(`<div class='latestnews-title'>Tin tức mới nhất trong ngày</div>`))

        for (var i = 0; i < data.length; i++) {
            var item = htmlToElement(
                `<div class="news-container">` +
                    `<a href=${data[i].link}><img class='news-img' src=${data[i].thumbnail} /></a>` +
                    `<div class="news-main" >` +
                        `<a href=${data[i].link} class="news-title" >${data[i].title}</a>` +
                        `<p class='news-content'>${data[i].content.split("</a>")[1]}<p>` +
                    `</div>` +
                `</div>`
            );
            content.appendChild(item);
        }

    }
</script>

<style>
.latestnews-title {
    font-size : 40px;
}

.news-container {
    display: flex;
    margin: 30px;
}

.news-img {
    height : 200px;
    width : auto;
    max-width: 300px;
}

a {
    margin-right: 10px;
}

.news-main {
    padding: unset;
    margin : 10px 0px 10px 50px;
}

.news-title {
    font-weight: bold;
    font-size: 1.6rem;
    padding: 5px 0px 5px 0px;
}

a.news-title:hover {
    text-decoration: underline;
}

.news-content {
    margin-top: 30px;
}
</style>
